Repository marcosdosea/QueroJobs, pull requests merged in 2022-08, with the labels that each got.

#9 Add::UI Resolve #5
  Requisitos/UI/Tela_001.jpg
  Requisitos/UI/Tela_002.jpg
  Requisitos/UI/Tela_003.jpg
  Requisitos/UI/Tela_004.jpg
  Requisitos/UI/Tela_005.jpg
  Requisitos/UI/Tela_006.jpg
  Requisitos/UI/Tela_007.jpg
  Requisitos/UI/Tela_008.jpg
  Requisitos/UI/Tela_009.jpg
  Requisitos/UI/Tela_010.jpg
  Requisitos/UI/Tela_011.png
  Requisitos/UI/Tela_012.jpg
  Requisitos/UI/Tela_013.png
  Requisitos/UI/Tela_014.png
  Requisitos/UI/Tela_015.png
  Requisitos/UI/Tela_016.jpg
  Requisitos/UI/Tela_017.jpg
  Requisitos/UI/Tela_018.jpg
  Requisitos/UI/Tela_019.jpg
  Requisitos/UI/Tela_020.jpg
  Requisitos/UI/Tela_021.jpg
  Requisitos/UI/Tela_022.jpg
  Requisitos/UI/Tela_023.jpg
  Requisitos/UI/Tela_024.jpg
  Requisitos/UI/Tela_025.jpg
  Requisitos/UI/Tela_026.jpg
  Requisitos/UI/Tela_027.jpg
  Requisitos/UI/Tela_028.jpg
Labels: good first issue

#10 Pasta e arquivo adicionados. Resolve #6.
  AnaliseProjeto/querojobs.mdj
Labels: good first issue

#12 Add::Requisitos Resolve #4
  Requisitos/Requisitos_funcionais_versao5.1.docx
  Requisitos/Requisitos_nao_funcionais3.0.docx
Labels: good first issue

#13 ADD:: Adicionando Documento de Visão . Resolve #2
  Gerenciamento/Documento de Visão - QueroJobs.docx
Labels: good first issue

#22 Add: DbSource and DER
  AnaliseProjeto/DER.mwb
  AnaliseProjeto/DER.mwb.bak
  AnaliseProjeto/DbSource.TXT
  AnaliseProjeto/DbSource.sql
Labels: good first issue

#25 Branch milena24
  AnaliseProjeto/DER.mwb
  AnaliseProjeto/DER.mwb.bak
  AnaliseProjeto/querojobs.mdj
  Codigo/bin/Debug/net6.0/QueroJobs.deps.json
  Codigo/bin/Debug/net6.0/QueroJobs.dll
  Codigo/bin/Debug/net6.0/QueroJobs.exe
  Codigo/bin/Debug/net6.0/QueroJobs.pdb
  Codigo/bin/Debug/net6.0/QueroJobs.runtimeconfig.json
  Codigo/bin/Debug/net6.0/QueroJobs.staticwebassets.runtime.json
  Codigo/bin/Debug/net6.0/appsettings.Development.json
  Codigo/bin/Debug/net6.0/appsettings.json
  Codigo/bin/Debug/net6.0/libman.json
  Codigo/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs
  Codigo/obj/Debug/net6.0/QueroJobs.AssemblyInfo.cs
  Codigo/obj/Debug/net6.0/QueroJobs.AssemblyInfoInputs.cache
  Codigo/obj/Debug/net6.0/QueroJobs.GeneratedMSBuildEditorConfig.editorconfig
  Codigo/obj/Debug/net6.0/QueroJobs.GlobalUsings.g.cs
  Codigo/obj/Debug/net6.0/QueroJobs.MvcApplicationPartsAssemblyInfo.cache
  Codigo/obj/Debug/net6.0/QueroJobs.RazorAssemblyInfo.cache
  Codigo/obj/Debug/net6.0/QueroJobs.RazorAssemblyInfo.cs
  Codigo/obj/Debug/net6.0/QueroJobs.assets.cache
  Codigo/obj/Debug/net6.0/QueroJobs.csproj.AssemblyReference.cache
  Codigo/obj/Debug/net6.0/QueroJobs.csproj.CoreCompileInputs.cache
  Codigo/obj/Debug/net6.0/QueroJobs.csproj.FileListAbsolute.txt
  Codigo/obj/Debug/net6.0/QueroJobs.dll
  Codigo/obj/Debug/net6.0/QueroJobs.genruntimeconfig.cache
  Codigo/obj/Debug/net6.0/QueroJobs.pdb
  Codigo/obj/Debug/net6.0/apphost.exe
  Codigo/obj/Debug/net6.0/ref/QueroJobs.dll
  Codigo/obj/Debug/net6.0/refint/QueroJobs.dll
  Codigo/obj/Debug/net6.0/scopedcss/Views/FuncionarioCrud/Formulario.cshtml.rz.scp.css
  Codigo/obj/Debug/net6.0/scopedcss/Views/Shared/_Layout.cshtml.rz.scp.css
  Codigo/obj/Debug/net6.0/scopedcss/bundle/QueroJobs.styles.css
  Codigo/obj/Debug/net6.0/scopedcss/projectbundle/QueroJobs.bundle.scp.css
  Codigo/obj/Debug/net6.0/staticwebassets.build.json
  Codigo/obj/Debug/net6.0/staticwebassets.development.json
  Codigo/obj/QueroJobs.csproj.nuget.dgspec.json
  Codigo/obj/QueroJobs.csproj.nuget.g.props
  Codigo/obj/QueroJobs.csproj.nuget.g.targets
  Codigo/obj/project.assets.json
  Codigo/obj/project.nuget.cache
  Codigo/obj/staticwebassets.pack.sentinel
Labels: enhancement

#44 Remove: bin and obj
  Codigo/bin/Debug/net6.0/QueroJobs.deps.json
  Codigo/bin/Debug/net6.0/QueroJobs.dll
  Codigo/bin/Debug/net6.0/QueroJobs.exe
  Codigo/bin/Debug/net6.0/QueroJobs.pdb
  Codigo/bin/Debug/net6.0/QueroJobs.runtimeconfig.json
  Codigo/bin/Debug/net6.0/QueroJobs.staticwebassets.runtime.json
  Codigo/bin/Debug/net6.0/appsettings.Development.json
  Codigo/bin/Debug/net6.0/appsettings.json
  Codigo/bin/Debug/net6.0/libman.json
  Codigo/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs
  Codigo/obj/Debug/net6.0/QueroJobs.AssemblyInfo.cs
  Codigo/obj/Debug/net6.0/QueroJobs.AssemblyInfoInputs.cache
  Codigo/obj/Debug/net6.0/QueroJobs.GeneratedMSBuildEditorConfig.editorconfig
  Codigo/obj/Debug/net6.0/QueroJobs.GlobalUsings.g.cs
  Codigo/obj/Debug/net6.0/QueroJobs.MvcApplicationPartsAssemblyInfo.cache
  Codigo/obj/Debug/net6.0/QueroJobs.RazorAssemblyInfo.cache
  Codigo/obj/Debug/net6.0/QueroJobs.RazorAssemblyInfo.cs
  Codigo/obj/Debug/net6.0/QueroJobs.assets.cache
  Codigo/obj/Debug/net6.0/QueroJobs.csproj.AssemblyReference.cache
  Codigo/obj/Debug/net6.0/QueroJobs.csproj.CoreCompileInputs.cache
  Codigo/obj/Debug/net6.0/QueroJobs.csproj.FileListAbsolute.txt
  Codigo/obj/Debug/net6.0/QueroJobs.dll
  Codigo/obj/Debug/net6.0/QueroJobs.genruntimeconfig.cache
  Codigo/obj/Debug/net6.0/QueroJobs.pdb
  Codigo/obj/Debug/net6.0/apphost.exe
  Codigo/obj/Debug/net6.0/ref/QueroJobs.dll
  Codigo/obj/Debug/net6.0/refint/QueroJobs.dll
  Codigo/obj/Debug/net6.0/scopedcss/Views/FuncionarioCrud/Formulario.cshtml.rz.scp.css
  Codigo/obj/Debug/net6.0/scopedcss/Views/Shared/_Layout.cshtml.rz.scp.css
  Codigo/obj/Debug/net6.0/scopedcss/bundle/QueroJobs.styles.css
  Codigo/obj/Debug/net6.0/scopedcss/projectbundle/QueroJobs.bundle.scp.css
  Codigo/obj/Debug/net6.0/staticwebassets.build.json
  Codigo/obj/Debug/net6.0/staticwebassets.development.json
  Codigo/obj/QueroJobs.csproj.nuget.dgspec.json
  Codigo/obj/QueroJobs.csproj.nuget.g.props
  Codigo/obj/QueroJobs.csproj.nuget.g.targets
  Codigo/obj/project.assets.json
  Codigo/obj/project.nuget.cache
  Codigo/obj/staticwebassets.pack.sentinel
Labels: enhancement

#51 Close #34 Resolve #49
  AnaliseProjeto/querojobs.mdj
  Requisitos/UI/Tela_029.png
Labels: enhancement

#60 Modificação na classe "Submeter Vaga Disponível"
  AnaliseProjeto/querojobs.mdj
Labels: enhancement

#62 Update: DER e diagrama do banco
  AnaliseProjeto/DER.mwb
  AnaliseProjeto/DER.mwb.bak
  AnaliseProjeto/querojobs.mdj
Labels: enhancement

#65 Refactor: Diagram de classes refatorado
  AnaliseProjeto/querojobs.mdj
Labels: enhancement

#66 Add: Atualização das telas
  Requisitos/UI/Tela_003.jpg
  Requisitos/UI/Tela_017.jpg
  Requisitos/UI/Tela_029.jpg
  Requisitos/UI/Tela_029.png
Labels: documentation

#67 ADD: Documento de Arquitetura
  AnaliseProjeto/Documento de Arquitetura - QueroJobs.docx
Labels: documentation
