Repository marcosdosea/QueroJobs, pull requests merged in 2022-10, with the labels that each got.

#190 PR da feature de vagas #143
  Codigo/QueroJobs/Core/SeedingService.cs
  Codigo/QueroJobs/Core/Services/IVacancyService.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CandidateController.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/VacancyController.cs
  Codigo/QueroJobs/QueroJobsWEB/Mappers/VacancyProfile.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/CandidateModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/VacancyModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Program.cs
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Vacancy/Create.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Vacancy/Delete.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Vacancy/Details.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Vacancy/Edit.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Vacancy/Index.cshtml
  Codigo/QueroJobs/Services/VacancyService.cs
Labels: feature

#192 ADD: correção de readme
  Codigo/README.md
Labels: fix

#200 [ADD] ➕Tests for use case Company
  Codigo/QueroJobs/QueroJobs.sln
  Codigo/QueroJobs/QueroJobsWEBTests/Controllers/CompanyControllerTests.cs
  Codigo/QueroJobs/QueroJobsWEBTests/QueroJobsWEBTests.csproj
  Codigo/QueroJobs/ServicesTests/CompanyServiceTests.cs
  Codigo/QueroJobs/ServicesTests/ServicesTests.csproj
Labels: unit test

#205 refactoring
  Codigo/QueroJobs/QueroJobsWEB/Views/Home/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Home/Index.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/partners.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/reset.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/site.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/styles.css
Labels: fix

#208 ADD: telas responsivas - já em produção
  Requisitos/UI/Mobile/Manter candidato 1.png
  Requisitos/UI/Mobile/Manter candidato 2.png
  Requisitos/UI/Mobile/Manter candidato 3.png
  Requisitos/UI/Mobile/Manter currículo.png
  Requisitos/UI/Mobile/Manter empresa 1.png
  Requisitos/UI/Mobile/Manter empresa 2.png
  Requisitos/UI/Mobile/Manter empresa 3.png
  Requisitos/UI/Mobile/Menu deslogado.png
  Requisitos/UI/Mobile/Menu user logado.png
  Requisitos/UI/Mobile/Sino notificação.png
  Requisitos/UI/Mobile/Tipo de cadastro.png
Labels: enhancement

#209 Caso de teste implementado para CompetenceController e CompetenceService
  Codigo/QueroJobs/QueroJobsWEBTests/Controllers/CompetenceControllerTests.cs
  Codigo/QueroJobs/ServicesTests/CompetenceServiceTests.cs
Labels: unit test

#210 Caso de uso Manter Instituição implementado
  Codigo/QueroJobs/Core/SeedingService.cs
  Codigo/QueroJobs/Core/Services/IInstitutionService.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/AdminController.cs
  Codigo/QueroJobs/QueroJobsWEB/Mappers/InstitutionProfile.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/AdminModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/InstitutionModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Program.cs
  Codigo/QueroJobs/QueroJobsWEB/Views/Admin/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Admin/InstitutionCreate.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Admin/InstitutionDelete.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Admin/InstitutionEdit.cshtml
  Codigo/QueroJobs/Services/InstitutionService.cs
Labels: feature

#212 Finalização do caso de teste de unidade para Course.
  Codigo/QueroJobs/QueroJobsWEBTests/Controllers/CourseControllerTests.cs
  Codigo/QueroJobs/ServicesTests/CourseServiceTests.cs
Labels: unit test

#216 ADD:: Vacancy tests
  Codigo/QueroJobs/QueroJobsWEBTests/Controllers/VacancyControllerTests.cs
  Codigo/QueroJobs/ServicesTests/VacancyServiceTests.cs
Labels: unit test

#221 Pull request parcial da tela de form
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CandidateController.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/FormModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Form.cshtml
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/site.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/styles.css
Labels: feature

#222 [Add] Utils and personalized data validations
  Codigo/QueroJobs/QueroJobs.sln
  Codigo/QueroJobs/Utils/CPFAttribute.cs
  Codigo/QueroJobs/Utils/CepAttribute.cs
  Codigo/QueroJobs/Utils/Methods.cs
  Codigo/QueroJobs/Utils/TelefoneCelularAttribute.cs
  Codigo/QueroJobs/Utils/TelefoneFixoAttribute.cs
  Codigo/QueroJobs/Utils/Utils.csproj
Labels: feature

#218 Revisar o cadastro de candidato
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CandidateController.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/CandidateModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Create.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Create.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/QuerojobsComponents.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/site.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/styles.css
Labels: feature

#226 FIX: cadastro de candidato
  AnaliseProjeto/DER.mwb
  Codigo/QueroJobs/Core/QueroJobsContext.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CandidateController.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/CandidateModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Program.cs
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Create.cshtml
Labels: fix

#223 Tela Admin
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CandidateController.cs
  Codigo/QueroJobs/QueroJobsWEB/Views/Admin/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Admin/Index.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Create.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Create.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/styles.css
  Codigo/QueroJobs/Services/CandidateService.cs
Labels: enhancement, feature
