Repository marcosdosea/QueroJobs, pull requests merged in 2022-09, with the labels that each got.

#72 [Fix] buscando empresa antes de inserir vaga
  AnaliseProjeto/querojobs.mdj
Labels: fix

#80 Relacionamento adicionado.
  AnaliseProjeto/querojobs.mdj
Labels: enhancement

#83 Fix: Antes de selecionar candidato, deve-se buscar as vagas #71
  AnaliseProjeto/querojobs.mdj
Labels: fix

#85 Fix: Para inserir uma vaga deve-se primeiro buscar a empresa
  AnaliseProjeto/querojobs.mdj
Labels: fix

#87 Fix: Consultar candidatos interessados não está seguindo o comportamento esperado
  AnaliseProjeto/querojobs.mdj
Labels: fix

#90 Branch joanne75
  AnaliseProjeto/querojobs.mdj
Labels: fix

#94 Branch kendy 89
  AnaliseProjeto/querojobs.mdj
Labels: feature

#96 ADD:: Diagrama de estados para Candidato
  AnaliseProjeto/querojobs.mdj
Labels: feature

#98 DER atualizado.
  AnaliseProjeto/querojobs.mdj
Labels: fix

#100 ADD:: Modelagem do banco e ajustes do DER
  AnaliseProjeto/DER.mwb
  AnaliseProjeto/DER.mwb.bak
  AnaliseProjeto/querojobs.mdj
Labels: feature

#105 Agora na tela de cadastrar vaga pode-se colocar quantidade.
  Requisitos/UI/Tela_017.jpg
Labels: enhancement

#149 [Add] Add Service CandidateService
  Codigo/QueroJobs/Core/Services/ICandidateService.cs
  Codigo/QueroJobs/Services/CandidateService.cs
Labels: feature

#151 [Update] Turned all methods in async
  Codigo/QueroJobs/Core/Services/ICompanyService.cs
  Codigo/QueroJobs/Services/CompanyService.cs
Labels: enhancement

#158 Atualização README
  README.md
Labels: documentation

#155 Implementação do caso de uso ManterCargo
  Codigo/QueroJobs/Core/Services/IRoleService.cs
  Codigo/QueroJobs/Services/RoleService.cs
Labels: enhancement, feature

#156 Branch_Ericles154
  Codigo/QueroJobs/QueroJobs.sln
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CompanyController.cs
  Codigo/QueroJobs/QueroJobsWEB/QueroJobsWEB.csproj
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Create.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Delete.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Details.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Edit.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml
  Codigo/QueroJobs/Services/CompanyService.cs
Labels: feature

#159 Implementação do caso de uso ManterCompetência
  Codigo/QueroJobs/Core/Services/ICompetenceService.cs
  Codigo/QueroJobs/Services/CompetenceService.cs
Labels: enhancement, feature

#162 [Add] add .editorconfig 🧹 clean code Resolve #161
  .gitignore
  Codigo/QueroJobs/.editorconfig
  Codigo/QueroJobs/Core/Candidate.cs
  Codigo/QueroJobs/Core/Candidatecompetence.cs
  Codigo/QueroJobs/Core/Candidateformation.cs
  Codigo/QueroJobs/Core/Candidateoccupationarea.cs
  Codigo/QueroJobs/Core/Candidaterole.cs
  Codigo/QueroJobs/Core/Candidatevacancy.cs
  Codigo/QueroJobs/Core/Company.cs
  Codigo/QueroJobs/Core/Competence.cs
  Codigo/QueroJobs/Core/Core.csproj
  Codigo/QueroJobs/Core/Course.cs
  Codigo/QueroJobs/Core/DTO/CandidateDTO.cs
  Codigo/QueroJobs/Core/Formation.cs
  Codigo/QueroJobs/Core/Formationcourse.cs
  Codigo/QueroJobs/Core/Formationinstitution.cs
  Codigo/QueroJobs/Core/Formationscholarity.cs
  Codigo/QueroJobs/Core/Formationvacancy.cs
  Codigo/QueroJobs/Core/Institution.cs
  Codigo/QueroJobs/Core/Occupationarea.cs
  Codigo/QueroJobs/Core/QueroJobsContext.cs
  Codigo/QueroJobs/Core/Role.cs
  Codigo/QueroJobs/Core/Scholarity.cs
  Codigo/QueroJobs/Core/Vacancy.cs
  Codigo/QueroJobs/Core/Vacancycompetence.cs
  Codigo/QueroJobs/Core/Vacancyformation.cs
  Codigo/QueroJobs/Core/Vacancyoccupationarea.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CompanyController.cs
Labels: feature

#164 ADD:: Injeções de dependência para RoleServices e CompetenceServices.
  Codigo/QueroJobs/QueroJobsWEB/Program.cs
Labels: enhancement

#166 FIX:: Alterando nomes de atributos do banco
  AnaliseProjeto/DER.mwb
  AnaliseProjeto/DER.mwb.bak
Labels: fix

#168 [Add] Add mapper and company mapper/model
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CompanyController.cs
  Codigo/QueroJobs/QueroJobsWEB/Mappers/CompanyProfile.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/CompanyModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Program.cs
  Codigo/QueroJobs/QueroJobsWEB/QueroJobsWEB.csproj
Labels: enhancement, feature

#170 [Add] Add Home Page
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Create.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Delete.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Details.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Edit.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Home/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Home/Privacy.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/Views/_ViewImports.cshtml
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/assets/images/landing__image-one.png
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/assets/images/landing__image-two.png
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/landing.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/partners.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/reset.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/styles.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/lib/jquery-validate/additional-methods.min.js
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/lib/jquery-validate/jquery.validate.js
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/lib/jquery-validate/jquery.validate.min.js
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/lib/jquery-validate/localization/messages_pt_BR.js
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/lib/jquery/jquery.js
Labels: update

#176 [UPDATE] Update views with validation
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Create.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Delete.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Details.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Edit.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Index.cshtml
Labels: update

#179 Implementado o caso de uso manter candidato
  Codigo/QueroJobs/Core/DTO/CandidateDTO.cs
  Codigo/QueroJobs/Core/SeedingService.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CandidateController.cs
  Codigo/QueroJobs/QueroJobsWEB/Mappers/CandidateProfile.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/CandidateModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Program.cs
  Codigo/QueroJobs/QueroJobsWEB/QueroJobsWEB.csproj
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Create.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Delete.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Details.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Edit.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml
Labels: feature

#183 Implementado Caso de Uso Manter Curso.
  Codigo/QueroJobs/Core/SeedingService.cs
  Codigo/QueroJobs/Core/Services/ICourseService.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CourseController.cs
  Codigo/QueroJobs/QueroJobsWEB/Mappers/CourseProfile.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/CourseModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Program.cs
  Codigo/QueroJobs/QueroJobsWEB/Views/Course/Create.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Course/Delete.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Course/Edit.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Course/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml
  Codigo/QueroJobs/Services/CourseService.cs
Labels: feature

#186 Branch ericles185
  AnaliseProjeto/DER.mwb
  AnaliseProjeto/DER.mwb.bak
Labels: fix

#187 Finalização dos casos de uso Role e Competence
  Codigo/QueroJobs/Core/SeedingService.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CompetenceController.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/RoleController.cs
  Codigo/QueroJobs/QueroJobsWEB/Mappers/CompetenceProfile.cs
  Codigo/QueroJobs/QueroJobsWEB/Mappers/RoleProfile.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/CompetenceModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/RoleModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Program.cs
  Codigo/QueroJobs/QueroJobsWEB/Views/Competence/Create.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Competence/Delete.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Competence/Edit.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Competence/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Role/Create.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Role/Delete.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Role/Edit.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Role/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml
Labels: feature, fix

#189 [Add] Package Microsoft.VisualStudio.Web.CodeGeneration.Design
  Codigo/QueroJobs/QueroJobsWEB/QueroJobsWEB.csproj
Labels: feature
