Repository marcosdosea/QueroJobs, pull requests merged in 2022-11, with the labels that each got.

#231 Add tela de login da empresa
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CandidateController.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CompanyController.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/LoginCompanyModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Login.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Login.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/_CompanyAside.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/_CompanyAside.cshtml.css
Labels: feature

#220 Classe Teste de Serviço Instituição.
  Codigo/QueroJobs/QueroJobsWEB/Controllers/AdminController.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/VacancyController.cs
  Codigo/QueroJobs/QueroJobsWEBTests/Controllers/AdminControllerTests.cs
  Codigo/QueroJobs/QueroJobsWEBTests/Controllers/CandidateControllerTests.cs
  Codigo/QueroJobs/ServicesTests/CandidateServiceTests.cs
  Codigo/QueroJobs/ServicesTests/CompanyServiceTests.cs
  Codigo/QueroJobs/ServicesTests/InstitutionServiceTests.cs
Labels: feature

#233 FIX:: Centralização e botões
  Codigo/QueroJobs/QueroJobsWEB/Views/Admin/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Admin/Index.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/QuerojobsComponents.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/styles.css
Labels: update, fix

#235 Add login candidato
  Codigo/QueroJobs/QueroJobsWEB/Controllers/AdminController.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CandidateController.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CompanyController.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/VacancyController.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/LoginCompanyModel.cs
  Codigo/QueroJobs/QueroJobsWEB/Views/Admin/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Admin/Index.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Login.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/Login.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/_CompanyAside.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Company/_CompanyAside.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/QuerojobsComponents.css
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/styles.css
  Codigo/QueroJobs/QueroJobsWEBTests/Controllers/AdminControllerTests.cs
  Codigo/QueroJobs/QueroJobsWEBTests/Controllers/CandidateControllerTests.cs
  Codigo/QueroJobs/ServicesTests/CandidateServiceTests.cs
  Codigo/QueroJobs/ServicesTests/CompanyServiceTests.cs
  Codigo/QueroJobs/ServicesTests/InstitutionServiceTests.cs
Labels: feature

#236 Add login candidate
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CandidateController.cs
  Codigo/QueroJobs/QueroJobsWEB/Models/LoginCandidateModel.cs
  Codigo/QueroJobs/QueroJobsWEB/QueroJobsWEB.csproj
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Login.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Login.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_candidateAside.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_candidateAside.cshtml.css
Labels: feature

#241 Refactoring Candidate aside login partial view
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Login.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/_CandidateAside.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/_candidateAside.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_LoginPartial.cshtml
  Codigo/QueroJobs/QueroJobsWEB/appsettings.json
Labels: enhancement

#242 Controladora de Candidatos Interessados
  Codigo/QueroJobs/QueroJobsWEB/Controllers/InterestedCandidatesController.cs
Labels: feature

#244 Troca do responsável por implementar o método obter candidatos interessados.
  Codigo/QueroJobs/Core/Services/ICompanyService.cs
  Codigo/QueroJobs/Core/Services/IVacancyService.cs
  Codigo/QueroJobs/Services/CompanyService.cs
  Codigo/QueroJobs/Services/VacancyService.cs
Labels: fix

#237 [ADD] Tela CRUD - Vacancy
  Codigo/QueroJobs/QueroJobsWEB/Views/Vacancy/Create.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Vacancy/Create.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/Views/Vacancy/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Vacancy/Index.cshtml.css
Labels: invalid, feature

#249 Hotfix Identidade
  AnaliseProjeto/dumpAutenticacao.sql
  Codigo/QueroJobs/Core/Aspnetrole.cs
  Codigo/QueroJobs/Core/Aspnetroleclaim.cs
  Codigo/QueroJobs/Core/Aspnetuser.cs
  Codigo/QueroJobs/Core/Aspnetuserclaim.cs
  Codigo/QueroJobs/Core/Aspnetuserlogin.cs
  Codigo/QueroJobs/Core/Aspnetuserrole.cs
  Codigo/QueroJobs/Core/Aspnetusertoken.cs
  Codigo/QueroJobs/Core/Candidate.cs
  Codigo/QueroJobs/Core/Candidatecompetence.cs
  Codigo/QueroJobs/Core/Candidateoccupationarea.cs
  Codigo/QueroJobs/Core/Candidaterole.cs
  Codigo/QueroJobs/Core/Candidatevacancy.cs
  Codigo/QueroJobs/Core/Company.cs
  Codigo/QueroJobs/Core/Competence.cs
  Codigo/QueroJobs/Core/Course.cs
  Codigo/QueroJobs/Core/Efmigrationshistory.cs
  Codigo/QueroJobs/Core/Formation.cs
  Codigo/QueroJobs/Core/Formationvacancy.cs
  Codigo/QueroJobs/Core/Institution.cs
  Codigo/QueroJobs/Core/Occupationarea.cs
  Codigo/QueroJobs/Core/QueroJobsContext.cs
  Codigo/QueroJobs/Core/Role.cs
  Codigo/QueroJobs/Core/Scholarity.cs
  Codigo/QueroJobs/Core/SeedingService.cs
  Codigo/QueroJobs/Core/Vacancy.cs
  Codigo/QueroJobs/Core/Vacancycompetence.cs
  Codigo/QueroJobs/Core/Vacancyoccupationarea.cs
  Codigo/QueroJobs/QueroJobsWEB/Areas/Identity/Pages/Account/Login.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Areas/Identity/Pages/Account/Login.cshtml.css
  Codigo/QueroJobs/QueroJobsWEB/Areas/Identity/Pages/Account/Manage/_Layout.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Areas/Identity/Pages/_ViewImports.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Controllers/AdminController.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CandidateController.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/CompanyController.cs
  Codigo/QueroJobs/QueroJobsWEB/Program.cs
  Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Login.cshtml
  Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml
  Codigo/QueroJobs/QueroJobsWEB/appsettings.json
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/site.css
Labels: fix
