Repository marcosdosea/QueroJobs, pull requests merged in 2023-03, with the labels that each got.

#267 Create RoleControllerTest
  Codigo/QueroJobs/QueroJobsWEBTests/Controllers/RoleControllerTests.cs
Labels: update, fix

#269 Implementação Iniciada.
  Codigo/QueroJobs/QueroJobsWEBTests/Controllers/AdminControllerTests.cs
Labels: feature, fix

#271 [Update] Updated Autentication Dump
  AnaliseProjeto/dumpAutenticacao.sql
Labels: update

#274 [Add] Selenium test Manter Empresa
  Codigo/QueroJobs/Core/SeedingService.cs
  Codigo/QueroJobs/QueroJobsWEB/Views/Home/Index.cshtml
  Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/QuerojobsComponents.css
  Testes/QueroJobs-ManterEmpresa.side
Labels: feature

#277 [Add] Selenium test Autenticar Usuario
  Testes/QueroJobs-AutenticarUsuario.side
Labels: feature
