Repository marcosdosea/QueroJobs, pull requests merged in 2023-02, with the labels that each got.

#253 [Add] Create Role TestUnits
  Codigo/QueroJobs/ServicesTests/RoleServiceTests.cs
Labels: feature, unit test

#251 [Update] UI
  Requisitos/UI/Tela_010.jpg
  Requisitos/UI/Tela_011.png
  Requisitos/UI/Tela_012.jpg
  Requisitos/UI/Tela_013.png
  Requisitos/UI/Tela_014.png
  Requisitos/UI/Tela_015.png
  Requisitos/UI/Tela_017.jpg
  Requisitos/UI/Tela_018.jpg
  Requisitos/UI/Tela_019.jpg
Labels: update

#255 Code cleanup
  Codigo/QueroJobs/Core/Aspnetrole.cs
  Codigo/QueroJobs/Core/Aspnetroleclaim.cs
  Codigo/QueroJobs/Core/Aspnetuser.cs
  Codigo/QueroJobs/Core/Aspnetuserclaim.cs
  Codigo/QueroJobs/Core/Aspnetuserlogin.cs
  Codigo/QueroJobs/Core/Aspnetuserrole.cs
  Codigo/QueroJobs/Core/Aspnetusertoken.cs
  Codigo/QueroJobs/Core/Candidate.cs
  Codigo/QueroJobs/Core/Candidatecompetence.cs
  Codigo/QueroJobs/Core/Candidateoccupationarea.cs
  Codigo/QueroJobs/Core/Candidaterole.cs
  Codigo/QueroJobs/Core/Candidatevacancy.cs
  Codigo/QueroJobs/Core/Company.cs
  Codigo/QueroJobs/Core/Competence.cs
  Codigo/QueroJobs/Core/Course.cs
  Codigo/QueroJobs/Core/Efmigrationshistory.cs
  Codigo/QueroJobs/Core/Formation.cs
  Codigo/QueroJobs/Core/Formationvacancy.cs
  Codigo/QueroJobs/Core/Institution.cs
  Codigo/QueroJobs/Core/Occupationarea.cs
  Codigo/QueroJobs/Core/QueroJobsContext.cs
  Codigo/QueroJobs/Core/Role.cs
  Codigo/QueroJobs/Core/Scholarity.cs
  Codigo/QueroJobs/Core/Vacancy.cs
  Codigo/QueroJobs/Core/Vacancycompetence.cs
  Codigo/QueroJobs/Core/Vacancyoccupationarea.cs
  Codigo/QueroJobs/QueroJobsWEB/Controllers/InterestedCandidatesController.cs
  Codigo/QueroJobs/ServicesTests/InstitutionServiceTests.cs
  Codigo/QueroJobs/ServicesTests/VacancyServiceTests.cs
Labels: enhancement

#258 Analisar os testes feitos na vacancy service
  Codigo/QueroJobs/ServicesTests/VacancyServiceTests.cs
Labels: enhancement, fix

#260 [Update] Campos agora tem valores proximos com a realidade
  Codigo/QueroJobs/QueroJobsWEBTests/Controllers/CandidateControllerTests.cs
Labels: enhancement, fix

#264 [Update] Campos agora tem valores proximos com a realidade
  Codigo/QueroJobs/QueroJobsWEBTests/Controllers/CandidateControllerTests.cs
Labels: enhancement, fix, unit test

#265 [Update] Campos próximos da realidade
  Codigo/QueroJobs/QueroJobsWEBTests/Controllers/CompanyControllerTests.cs
Labels: update
